version: "3.9"
    
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content 
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'